<?php
/* DO NOT EDIT THIS FILE. */

/*If you want to make changes, copy it to /application/config and edit it there.
 *That file will override this one.
 */
 
/*This document defines the authorization level of every route. Routes not
 *explicity specified in this or another file are considered to be admin only.
 *
 *The syntax is
 *$routes[controller][action] = authorization level;
 */

 $routes = [];

 //always allow css, js and images
 $routes["application"]["css"] = TE_AUTH_PUBLIC;
 $routes["application"]["js"] = TE_AUTH_PUBLIC;
 $routes["application"]["img"] = TE_AUTH_PUBLIC;

 //home controller
 $routes["home"]["index"] = TE_AUTH_PUBLIC;

 ?>
